-define(LOG_DEBUG(Format, Args), ems_logger:debug(Format,Args)).
-define(LOG_INFO(Format, Args), ems_logger:info(Format,Args)).
-define(LOG_WARN(Format, Args), ems_logger:warn(Format,Args)).
-define(LOG_ERROR(Format, Args), ems_logger:error(Format,Args)).
